name: coreutils

on: workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf \
            automake \
            autopoint \
            bison \
            gperf \
            gettext \
            texinfo \
            rsync \
            wget \
            git \
            perl \
            m4

      - name: clone coreutils
        run: |
          git clone https://github.com/coreutils/coreutils.git
          cd coreutils
          ./bootstrap

      - name: configure
        run: |
          cd coreutils
          mkdir build
          cd build
          ../configure

      - name: build
        run: |
          cd coreutils/build
          make -j"$(nproc)"
